<?php
function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Cipher Game',
        'page callback' => 'drupal_get_form',
        'page argument' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success_page'] = array(
        'title' => 'Success',
       'page callback' => 'cipher_success',
       'access callback' => TRUE,
       'type' => MENU_CALLBACK,
   );
   return $items;
}

function cipher_form() {
    $form['message'] = array(
        '#title' => 'Enter a sentence',
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_sentence'),
    );
    $form['direction'] = array(
        '#title' => 'Enter a direction',
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_direction'),
    );
    $form['number_of_moves'] = array(
        '#title' => 'Enter a number',
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer_positive', 'element_validate_number_range'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go!',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $message = strtolower($form_state['values']['sentence']);
    $direction = strtolower($form_state['values']['direction']);
    $number_of_moves = $form_state['values']['number_of_moves'];
    $letter_array = str_split($message);
    $encoded_message = array();

    $alphabet =  array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
    //$punctuation = array('!', ',', '.', '?', '"', '""', '(', ')', '/', ';', ':');
    foreach ($letter_array as $letter) {
    	if (in_array($letter, $alphabet)) {
    		if ($direction === "right") {
    			$index = array_search($letter, $alphabet) + $number_of_moves;
    			if($index > count($alphabet)) {
    				$index = $index % count($alphabet);
    				array_push($encoded_message, $alphabet[$index]);
    			} else {
    				array_push($encoded_message, $alphabet[$index]);
    			}
    		} elseif ($direction === "left") {
    			$reversed_alphabet_array = array_reverse($alphabet);
    			$letter_index = array_search($letter, $reversed_alphabet_array) + $number_of_moves;
    			if($index > count($alphabet)) {
    				$index = $index % count($alphabet);
    				array_push($encoded_message, $reversed_alphabet_array[$index]);
    			} else {
    				array_push($encoded_message, $reversed_alphabet_array[$index]);
    			}
    		}
    	} else {
    		array_push($encoded_message, $letter);
    	}
    }
    $encoded_message = implode($encoded_message);
    $_SESSION['cipher_output'] = $encoded_message;
    $form_state['redirect'] = 'cipher_success_page';
}
function cipher_success() {
    $output = $_SESSION['$encpded_message'];
    return "Your encoded message is: <b>$output</b>";
}
